# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc3695f97a1c965d1ecd9c0773379b68147758802be9dcfda4d6acd9991a9c15c5bd972ae03da0ef5dc4b53124eace8b55e6cb19c0812ab58c5727917fcc984

test:
  secret_key_base: 584a1edcfd213534e6d5b0db9255f81e62e607aa683ebb8deae6796459e81f81a17f2d2c49e05cced06e88c53bffe315b3cf2ca0d5972f58cd2a3a54edc8fe8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
